#!/bin/bash
# Convert ELF-files generated by UPMEM's toolchain into a subkernel
# that can be loaded by the IME loader.

function be_to_le {
  printf "$1" | xxd -p -r | xxd -e -g $2 | awk '{ print $2 }'
}

if (( $# != 2 ));
then
  echo "Usage: ./sk.sh <input elf file> <output sk file>";
  echo $#;
  exit 1;
fi

if which dpu-clang > /dev/null 2> /dev/null;
then
  llvm-objcopy -O binary --only-section .text /input.elf /tmp/iram.bin
  llvm-objcopy -O binary --only-section .data /input.elf /tmp/wram.bin

  IRAM_SIZE_N=$(ls -l /tmp/iram.bin | awk '{ print $5 }')
  WRAM_SIZE_N=$(ls -l /tmp/wram.bin | awk '{ print $5 }')

  IRAM_SIZE=$(be_to_le $(printf "%08x" $(( IRAM_SIZE_N / 2048 ))) 4)
  WRAM_SIZE=$(be_to_le $(printf "%08x" $(( WRAM_SIZE_N / 2048 ))) 4)

  MAGIC="A5A5A5A5";
  MAC=$(printf "%032x" 0)
  IV=$(printf "%024x" 0)
  SIZE_AAD=$(be_to_le $(printf "%08x" 0) 4)
  SIZE=$(be_to_le $(printf "%08x" $(( 64 + IRAM_SIZE_N + WRAM_SIZE_N ))) 4)
  PAD=$(printf "%032x" 0)

  HEADER=$(printf "%s%s%s%s%s%s%s%s" $MAGIC $MAC $IV $SIZE_AAD $SIZE $IRAM_SIZE $WRAM_SIZE $PAD)
  echo $HEADER | xxd -p -r > /output.sk

  cat /tmp/iram.bin >> /output.sk
  cat /tmp/wram.bin >> /output.sk
else
  touch $2;
  docker run -it \
    --mount type=bind,src=$0,dst=/script.sh,ro \
    --mount type=bind,src=$1,dst=/input.elf,ro \
    --mount type=bind,src=$2,dst=/output.sk \
    fabianvanrissenbeck/upmem:latest /script.sh $1 $2
fi

